### ISSUE TITLE
Similar package, are you familiar with it?

### ISSUE THREAD

**Issue by dmitshur** [tv42/becky#2]
Hi @tv42,

This package looks similar to https://github.com/shurcooL/vfsgen.

Similarities include:
- Both are meant to be used via `go generate` directives.
- Both have a development mode activated via `-tags=dev` build tag.
  - **Edit:** Whoops, this part isn't actually a part of vfsgen, but it can be done when using it.
- Both are meant to be be friendly to `net/http` package.
  - Difference is becky individual files implement `http.Handler`, while vfsgen ouput implements `http.FileSystem` that can be used with `http.FileServer`.
- Both implement some fields (ETag/Last-Modified) for caching.

I just wanted to ask if you're aware of `vfsgen` already?

**Comment by tv42** [comment]
I can't find vfsgen in my bookmarks, so I may or may not have been aware of it.

I don't want to be forced into accessing the assets via a filesystem abstraction. Becky makes that opt-in; your wrapper function can add the asset to a filesystem, if you want, but you can also just use it directly as a variable, or register it into some other container. For example, your templates could all register themselves under one one parent template.

**Comment by dmitshur** [comment]
Fair enough, thanks for the explanation. :)

To clarify, is the reason that you're okay with direct variable access for assets because `becky` doesn't do gzip compression? It seems directly accessing the underlying data without going through virtual filesystem abstraction is less useful if it's (optionally) gzip compressed.

FWIW, the way I approach templates is by taking the standard funcs but adding an `http.FileSystem` parameter, see [`vfstemplate`](https://godoc.org/github.com/shurcooL/go/vfs/httpfs/html/vfstemplate). So my template loading code looks almost the same as when loading normal templates from disk, just with 1 extra parameter:

``` Go
t := template.New("").Funcs(template.FuncMap{...})
t, err := vfstemplate.ParseGlob(fs, t, "/assets/*.tmpl")
```

**Comment by tv42** [comment]
Well, my file system knows how to compress things already, so I don't need gzip inside my executable. But more than that, it's the style of accessing things, more than just templates. You want to use the embedded asset? It's right there, ready to be written to a socket, no APIs to jump through.
