### ISSUE TITLE
Files with non-identifier characters lead to incorrectly generated source code

### ISSUE THREAD

**Issue by echlebek** [tv42/becky#3]
To reproduce, just include an asset with a dash in it. A file that does not compile will be generated on `go generate`.

I see there is a way to explicitly name the var that gets generated, but I think this should cause `go generate` to fail, perhaps with a message telling the user to use an explicit var name.

**Comment by dmitshur** [comment]
Or just sanitize the variable names by default to avoid invalid characters.

**Comment by echlebek** [comment]
Sanitizing the variable creates the potential for naming collisions, so the simplest thing is to just reject them.

**Comment by tv42** [comment]
Yes, rejecting non-identifier names sounds like the right thing to do.
