### ISSUE TITLE
"unknown asset field 'etag' in struct literal" error with -tags=dev.

### ISSUE THREAD

**Issue by dmitshur** [tv42/becky#4]
I ran into this problem, which appears to be a bug, so I'm reporting it for your information:

I had a simple `main.go` file:

``` Go
//go:generate -command asset go run asset.go
//go:generate asset sample.txt

package main

import "fmt"

func txt(a asset) string {
    return a.Content
}

func main() {
    fmt.Println("sample.txt:", sample)
}
```

And a `sample.txt` file in the same folder with a short string. And I copied the latest version of `asset.go` from becky.

Then I did `go generate`.

It worked fine with `go build -o /tmp/o && /tmp/o`.

But when I did `go build -tags=dev -o /tmp/o && /tmp/o` I got the following compile error:

```
./sample.txt.gen.go:7: unknown asset field 'etag' in struct literal
```

I am guessing it's a regression after https://github.com/tv42/becky/commit/18e717cf1c43992f7febee24b0fedd5257564b12.

The `sample.txt.gen.go` file has:

``` Go
var sample = txt(asset{Name: "sample.txt", ..., etag: `"jYGplZ7kluU="`})
```

But `asset_dev.gen.go` doesn't have `etag` field in:

``` Go
type asset struct {
    Name    string
    Content string
    // don't bother precomputing ETag if we're reloading from disk
}
```

**Comment by dmitshur** [comment]
@tv42, is it intentional that you're [not watching](https://github.com/tv42/becky/watchers) your own repository? Given that's the case, I expect you not to be notified of this new issue unless I explicitly mention you.

**Comment by tv42** [comment]
No, that's a Github oddity. Notifications are often flaky for me.
