### ISSUE TITLE
go generate on get

### ISSUE THREAD

**Issue by kaihendry** [tv42/becky#5]
Hi, how do I avoid `undefined: asset` when I `go get github.com/unee-t/invite`?

https://github.com/unee-t/invite/blob/master/asset.go is there as you advised ..

https://gist.github.com/kaihendry/96cd9638443a19fbf584f0738f0a0b85

Using go version go1.9.4 linux/amd64

Thank you!

**Comment by tv42** [comment]
Commit the generated files.
