### ISSUE TITLE
Adding assets from non-package dir

### ISSUE THREAD

**Issue by myslak71** [tv42/becky#6]
Hey!
Let's say that my project structure looks as follows:
```
--project
    --src
          main.go
    --static
          index.html
```

Is there a way that index.html may be added as asset in main.go file?

Using:
`//go:generate go run github.com/tv42/becky ../static/index.html`
causes:
```
becky: cannot load package: go [list -e -json -compiled=false -test=false -export=false -deps=false -find=true -- ../../]: exit status 1: build ../..: cannot find module for path ../..
exit status 1
main.go:9: running "go": exit status 1
```

**Comment by tv42** [comment]
No, becky is intentionally simple and writes the generated code next to the file passed in. This is a mechanism for avoiding configurability and complexity in general.

What I've done with many projects is make the assets a Go package. Works great!
